default: &default
  workdir_root: &workdir_root
    /root/gatsby-ecommerce-pwa

  docker:
    - image: node:6.0.0
  working_directory: *workdir_root

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workdir_root

  restore_cache: &restore_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

  save_cache: &save_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

version: 2
jobs:
  lint:
    <<: *default
    steps:
      - checkout
      # Download and cache dependencies
      - *restore_cache
      - run: npm install
      - *save_cache
      - run:
          name: lint
          command: npm run lint

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/