default: &default
  workdir_root: &workdir_root
    /root/gatsby-ecommerce-pwa

  docker:
    - image: node:6.0.0
  working_directory: *workdir_root

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workdir_root

version: 2
jobs:
  lint:
    <<: *default
    steps:
      - checkout
      - run: npm install
      - run:
          name: lint
          command: npm run lint

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/